
#Install Packages
```{r}
#install.packages("factoextra")
#install.packages("forcats")
```



```{r}
library(readr)
library(tidyverse)
library(factoextra)
library(forcats)
```


```{r}
possum_raw <- read_csv("possum.csv")
#View(possum_raw)
```


```{r}

possum <- data.frame(possum_raw, row.names = 1)
#View(possum)
summary(possum)
```


```{r}
possum_clean = na.omit(possum)
str(possum_clean)
summary(possum_clean)

```




```{r}
possum_pca = subset(possum_clean, select = -c(site, Pop, sex))
possum.pca = prcomp(possum_pca, center = TRUE, scale. = TRUE)
summary(possum.pca)
#View(possum.pca$rotation)
possum.pca$rotation
```



```{r}
PCNames = c("age", "hdlngth", "skullw", "totlngth", "taill", "footlgth", "earconch", "eye", "chest", "belly")
```


```{r}
gradient_colors = c("#00AFBB", "#E7B800", "#FC4E07")
```



```{r}
PC1 = possum.pca$rotation[1:10]
PC1_DF = tibble(PCNames, PC1)
str(PC1_DF)
#View(PC1_DF)
```


```{r}
PC2 = possum.pca$rotation[11:20]
PC2_DF = tibble(PCNames, PC2)
str(PC2_DF)
```


```{r}
PC3 = possum.pca$rotation[21:30]
PC3_DF = tibble(PCNames, PC3)
str(PC3_DF)
```

```{r}
ggplot(PC1_DF, aes(x = fct_reorder(PCNames,PC1) , y = PC1)) + 
  geom_col(aes(fill = abs(PC1)))+
  labs(x = "Variable", y = "Effect on PC1", title = 'Variable Importance Bar Graph: All Possums PC1', fill = "Contribution to PC1")+
  scale_fill_gradientn(colors = gradient_colors)
```



```{r}
ggplot(PC2_DF, aes(x = fct_reorder(PCNames,PC2) , y = PC2)) + 
  geom_col(aes(fill = abs(PC2))) +
  labs(x = "Variable", y = "Effect on PC2", title = 'Variable Importance Bar Graph: All Possums PC2', fill = "Contribution to PC2")+
  scale_fill_gradientn(colors = gradient_colors)

```


```{}
ggplot(PC3_DF, aes(x = fct_reorder(PCNames,PC3) , y = PC3)) + 
  geom_col() +
  labs(x = "Variable", y = "Effect on PC3")

```




```{r}

fviz_eig(possum.pca, barfill = "#6efafb")
fviz_pca_ind(possum.pca,
             axes = c(2,1),
             col.ind = "cos2", # Color by quality of representation
             gradient.cols = gradient_colors,
             repel = TRUE #Avoid text overlapping
             )


fviz_pca_ind(possum.pca,
             axes = c(2,1),
             col.ind = "cos2", # Color by quality of representation
             gradient.cols = gradient_colors,
             repel = TRUE #Avoid text overlapping
             )

fviz_pca_var(possum.pca,
             axes = c(2,1),
             col.var = "contrib", # Color by contributions to the PC
             gradient.cols = c("#00AFBB", "#E7B800", "#FC4E07"),
             repel = TRUE #Avoid text overlapping
             )

fviz_pca_biplot(possum.pca, repel = TRUE,
                axes = c(2,1),
                col.var = "#2E9FDF", # Variables color
                col.ind = "#696969" #Individuals color
                )

fviz_pca_biplot(possum.pca, repel = TRUE,
                axes = c(2,1),
                col.var = "contrib", # Color by contributions to the PC
                gradient.cols = gradient_colors,
                title = 'PCA Biplot of All Possums'
                )
```


```{r}
biplot(possum.pca, choices = 2:1, scale = 1, pc.biplot = FALSE)
```


```{r}
coord = possum.pca$x # pulls out just the info from the pca results
plot(coord[,1], coord[,2]) # plots the first two axes of the pca

plot(coord[,1], coord[,2], cex= 0.1*possum_pca$age) # now the symbol size tells you age

possum_pca$sex = possum_clean$sex
str(possum_pca)
plot(coord[,1], coord[,2], cex= 0.1*possum_pca$age, pch=possum_pca$sex)
#text(coord[,1], coord[,2], row.names(possum_pca))
plot(coord[,2], coord[,1], pch=possum_pca$site)
possum_pca$site = as.character(possum_clean$site)
possum_pca$Pop = possum_clean$Pop
plot(coord[,2], coord[,1], pch=possum_pca$Pop)
```



































