```{r}
#import("factoextra")
library(factoextra)
library(readr)
winequality_red <- read_delim("winequality-red.csv", 
    delim = ";", escape_double = FALSE, trim_ws = TRUE, 
    skip = 1)
#View(winequality_red)
```
```{r}
red_wine.pca <- prcomp(winequality_red, center = TRUE,scale. = TRUE)
summary(red_wine.pca)
summary(winequality_red)
str(winequality_red)
```
```{r}
fviz_eig(red_wine.pca)
fviz_pca_ind(red_wine.pca,
             col.ind = "cos2", # Color by the quality of representation
             gradient.cols = c("#00AFBB", "#E7B800", "#FC4E07"),
             repel = TRUE     # Avoid text overlapping
)
```
```{r}
fviz_pca_var(red_wine.pca,
             col.var = "contrib", # Color by contributions to the PC
             gradient.cols = c("#00AFBB", "#E7B800", "#FC4E07"),
             repel = TRUE     # Avoid text overlapping
)
```
```{r}
fviz_pca_biplot(red_wine.pca, repel = TRUE,
                col.var = "#2E9FDF", # Variables color
                col.ind = "#696969"  # Individuals color
)
```
```{r}
biplot(red_wine.pca, choices = 1:2, scale = 1, pc.biplot = FALSE)
```


```{r}
coord<-red_wine.pca$x 	#pulls out just the plotting information from the pca results
plot(coord[,1], coord[,2]) 	#plots the first two axes of the pca
plot(coord[,1], coord[,2], cex=0.1*winequality_red$quality) 	#Now the symbol size tells you mpg

#text(coord[,1], coord[,2], row.names(mtcars)) 
```
```{r}
#remove quality
redwine_no_quality = subset(winequality_red, select = -c(quality))
red_wine_no_qual.pca <- prcomp(redwine_no_quality, center = TRUE,scale. = TRUE)
summary(red_wine_no_qual.pca)
```
```{r}
fviz_eig(red_wine_no_qual.pca)
fviz_pca_ind(red_wine_no_qual.pca,
             col.ind = "cos2", # Color by the quality of representation
             gradient.cols = c("#00AFBB", "#E7B800", "#FC4E07"),
             repel = TRUE     # Avoid text overlapping
)
```


```{r}
fviz_pca_var(red_wine_no_qual.pca,
             col.var = "contrib", # Color by contributions to the PC
             gradient.cols = c("#00AFBB", "#E7B800", "#FC4E07"),
             repel = TRUE     # Avoid text overlapping
)
```


```{r}
fviz_pca_biplot(red_wine_no_qual.pca, repel = TRUE,
                col.var = "#2E9FDF", # Variables color
                col.ind = "#696969"  # Individuals color
)
```


```{r}
biplot(red_wine_no_qual.pca, choices = 1:2, scale = 1, pc.biplot = FALSE)

coord<-red_wine_no_qual.pca$x 	#pulls out just the plotting information from the pca results
plot(coord[,1], coord[,2]) 	#plots the first two axes of the pca
plot(coord[,1], coord[,2], cex=0.1*winequality_red$quality) 	#Now the symbol size tells you mpg
#text(coord[,1], coord[,2], row.names(mtcars)) 
```

