
```{r}
library(readr)
library(tidyverse)
library(factoextra)
library(forcats)
```


```{r}
possum_raw <- read_csv("possum.csv")
#View(possum_raw)
```


```{r}

possum <- data.frame(possum_raw, row.names = 1)
possum$site = as.factor(possum$site)
possum$Pop = as.factor(possum$Pop)
possum$sex = as.factor(possum$sex)
#View(possum)
summary(possum)
```


```{r}
possum_clean = na.omit(possum)
str(possum_clean)
summary(possum_clean)

```


```{r}
V_Possum <- possum_clean[possum_clean$Pop == "Vic", ]
O_Possum <- possum_clean[possum_clean$Pop == "other", ]
str(V_Possum)
str(O_Possum)
#summary(V_Possum)
#summary(O_Possum)
V_Possum_Numeric = subset(V_Possum, select = -c(Pop, sex, site))
O_Possum_Numeric = subset(O_Possum, select = -c(Pop, sex, site))
str(V_Possum)
#str(O_Possum)
#summary(V_Possum)
#summary(O_Possum)
```


```{r}
#Vic possum PCA
V_Possum.pca <- prcomp(V_Possum_Numeric, center = TRUE,scale. = TRUE)
summary(V_Possum.pca)

fviz_eig(V_Possum.pca)
fviz_pca_ind(V_Possum.pca,
             axes = c(2,1),
             col.ind = "cos2", # Color by the quality of representation
             gradient.cols = c("#00AFBB", "#E7B800", "#FC4E07"),
             repel = TRUE     # Avoid text overlapping
)

fviz_pca_var(V_Possum.pca,
             axes = c(2,1),
             col.var = "contrib", # Color by contributions to the PC
             gradient.cols = c("#00AFBB", "#E7B800", "#FC4E07"),
             repel = TRUE     # Avoid text overlapping
)

fviz_pca_biplot(V_Possum.pca,
                axes = c(2,1),
                repel = TRUE,
                col.var = "#2E9FDF", # Variables color
                col.ind = "#696969"  # Individuals color
)

fviz_pca_biplot(V_Possum.pca, repel = TRUE,
                axes = c(2,1),
                col.var = "contrib", # Color by contributions to the PC
                gradient.cols = c("#00AFBB", "#E7B800", "#FC4E07"),
                )

```

```{r}
#Some plots for Victoria Possums
coord = V_Possum.pca$x # pulls out just the info from the pca results
plot(coord[,1], coord[,2]) # plots the first two axes of the pca

plot(coord[,1], coord[,2], cex= 0.1*V_Possum$age) # now the symbol size tells you age


V_Possum.pca$sex = as.character(V_Possum$sex)
str(V_Possum.pca)
plot(coord[,1], coord[,2], pch=V_Possum.pca$sex)

#text(coord[,1], coord[,2], row.names(possum_pca))
# plot(coord[,1], coord[,2], pch=possum_pca$sex)

V_Possum.pca$site = as.character(V_Possum$site)
plot(coord[,1], coord[,2], pch=V_Possum.pca$site)
# possum_pca$Pop = possum_clean$Pop
# plot(coord[,1], coord[,2], pch=possum_pca$Pop)
```







```{r}
#Other Possum PCA

O_Possum.pca <- prcomp(O_Possum_Numeric, center = TRUE,scale. = TRUE)
summary(V_Possum.pca)

fviz_eig(O_Possum.pca)
fviz_pca_ind(O_Possum.pca,
             axes = c(2,1),
             col.ind = "cos2", # Color by the quality of representation
             gradient.cols = c("#00AFBB", "#E7B800", "#FC4E07"),
             repel = TRUE     # Avoid text overlapping
)

fviz_pca_var(O_Possum.pca,
             axes = c(2,1),
             col.var = "contrib", # Color by contributions to the PC
             gradient.cols = c("#00AFBB", "#E7B800", "#FC4E07"),
             repel = TRUE     # Avoid text overlapping
)

fviz_pca_biplot(O_Possum.pca,
                axes = c(2,1),
                repel = TRUE,
                col.var = "#2E9FDF", # Variables color
                col.ind = "#696969"  # Individuals color
)

fviz_pca_biplot(O_Possum.pca, repel = TRUE,
                axes = c(2,1),
                col.var = "contrib", # Color by contributions to the PC
                gradient.cols = c("#00AFBB", "#E7B800", "#FC4E07"),
                )

```


```{r}
coord = O_Possum.pca$x # pulls out just the info from the pca results
plot(coord[,1], coord[,2]) # plots the first two axes of the pca

plot(coord[,1], coord[,2], cex= 0.1*O_Possum$age) # now the symbol size tells you age

O_Possum.pca$sex = as.character(O_Possum$sex)
plot(coord[,1], coord[,2], pch=O_Possum.pca$sex)
# #text(coord[,1], coord[,2], row.names(possum_pca))
# plot(coord[,1], coord[,2], pch=possum_pca$sex)

O_Possum.pca$site = as.character(O_Possum$site)
plot(coord[,1], coord[,2], pch=O_Possum.pca$site)
# possum_pca$Pop = possum_clean$Pop
# plot(coord[,1], coord[,2], pch=possum_pca$Pop)
```



```{r}
PCNames = c("age", "hdlngth", "skullw", "totlngth", "taill", "footlgth", "earconch", "eye", "chest", "belly")
```


```{r}
V_PC1 = V_Possum.pca$rotation[1:10]
V_PC1_DF = tibble(PCNames, V_PC1)
str(V_PC1_DF)
#View(PC1_DF)
```


```{r}
V_PC2 = V_Possum.pca$rotation[11:20]
V_PC2_DF = tibble(PCNames, V_PC2)
str(V_PC2_DF)
```


```{r}
V_PC3 = V_Possum.pca[21:30]
V_PC3_DF = tibble(PCNames, V_PC3)
str(V_PC3_DF)
```

```{r}
ggplot(V_PC1_DF, aes(x = fct_reorder(PCNames,V_PC1) , y = V_PC1)) + 
  geom_col()+
  labs(x = "Variable", y = "Effect on V_PC1")

```



```{r}
ggplot(V_PC2_DF, aes(x = fct_reorder(PCNames,V_PC2) , y = V_PC2)) + 
  geom_col() +
  labs(x = "Variable", y = "Effect on V_PC2")

```


```{}
ggplot(V_PC3_DF, aes(x = fct_reorder(PCNames,V_PC3) , y = V_PC3)) + 
  geom_col() +
  labs(x = "Variable", y = "Effect on V_PC3")

```






```{r}
O_PC1 = O_Possum.pca$rotation[1:10]
O_PC1_DF = tibble(PCNames, O_PC1)
str(O_PC1_DF)
#View(PC1_DF)
```


```{r}
O_PC2 = O_Possum.pca$rotation[11:20]
O_PC2_DF = tibble(PCNames, O_PC2)
str(O_PC2_DF)
```


```{r}
O_PC3 = O_Possum.pca[21:30]
O_PC3_DF = tibble(PCNames, O_PC3)
str(O_PC3_DF)
```

```{r}
ggplot(O_PC1_DF, aes(x = fct_reorder(PCNames,O_PC1) , y = O_PC1)) + 
  geom_col()+
  labs(x = "Variable", y = "Effect on O_PC1")

```



```{r}
ggplot(O_PC2_DF, aes(x = fct_reorder(PCNames,O_PC2) , y = O_PC2)) + 
  geom_col() +
  labs(x = "Variable", y = "Effect on O_PC2")

```


```{}
ggplot(O_PC3_DF, aes(x = fct_reorder(PCNames,O_PC3) , y = O_PC3)) + 
  geom_col() +
  labs(x = "Variable", y = "Effect on O_PC3")

```


