
```{r}
library(readr)
possum <- read_csv("possum.csv")
#View(possum)
```


```{r}
possum_nocase = subset(possum, select = -c(case))
#View(possum_nocase)
#str(possum_nocase)
#summary(possum_nocase)
```


```{r}
possum_clean = na.omit(possum)
summary(possum_clean)
```


#Install Packages
```{r}
#install.packages("factoextra")
```

#Libraries
```{r}
library(factoextra)
library(ggplot2)
```



```{r}
dimnames(possum_clean)
possum.pca = prcomp(possum_clean, center = TRUE, scale. = TRUE)
summary(possum.pca)
```


```{r}

fviz_eig(possum.pca)
fviz_pca_ind(possum.pca,
             col.ind = "cos2", # Color by quality of representation
             gradient.cols = c("#00AFBB", "#E7B800", "#FC4E07"),
             repel = TRUE #Avoid text overlapping
             )
```


```{r}
fviz_pca_var(possum.pca,
             col.var = "contrib", # Color by contributions to the PC
             gradient.cols = c("#00AFBB", "#E7B800", "#FC4E07"),
             repel = TRUE #Avoid text overlapping
             )
```


```{r}
fviz_pca_biplot(possum.pca, repel = TRUE,
                col.var = "#2E9FDF", # Variables color
                col.ind = "#696969" #Individuals color
                )
```


```{r}
biplot(possum.pca, choices = 1:2, scale = 1, pc.biplot = FALSE)
```


```{r}
coord = possum.pca$x # pulls out just the info from the pca results
plot(coord[,1], coord[,2]) # plots the first two axes of the pca
text(coord[,1], coord[,2], row.names(possum_clean))
plot(coord[,1], coord[,2], cex= 0.1*possum_clean$age) # now the symbol size tells you mpg
text(coord[,1], coord[,2], row.names(possum_clean))
```

































































