
#Install Packages
```{r}
#install.packages("factoextra")
```



```{r}
library(readr)
library(tidyverse)
library(factoextra)
```


```{r}
whitewine_raw <- read_delim("winequality-white.csv", 
    delim = ";", escape_double = FALSE, trim_ws = TRUE, 
    skip = 1)
#View(whitewine_raw)
summary(whitewine_raw)
str(whitewine_raw)
```


```{r}
whitewine_pca = data.frame(whitewine_raw)
#view(whitewine_pca)
whitewine.pca = prcomp(whitewine_pca, center = TRUE, scale. = TRUE)
summary(whitewine.pca)
#View(whitewine.pca$rotation)
whitewine.pca$rotation

```


```{r}

fviz_eig(whitewine.pca)
fviz_pca_ind(whitewine.pca,
             col.ind = "cos2", # Color by quality of representation
             gradient.cols = c("#00AFBB", "#E7B800", "#FC4E07"),
             repel = TRUE #Avoid text overlapping
             )
```


```{r}
fviz_pca_var(whitewine.pca,
             col.var = "contrib", # Color by contributions to the PC
             gradient.cols = c("#00AFBB", "#E7B800", "#FC4E07"),
             repel = TRUE #Avoid text overlapping
             )
```


```{r}
fviz_pca_biplot(whitewine.pca, repel = TRUE,
                col.var = "#2E9FDF", # Variables color
                col.ind = "#696969" #Individuals color
                )
```


```{r}
biplot(whitewine.pca, choices = 1:2, scale = 1, pc.biplot = FALSE)
```


```{r}
coord = whitewine.pca$x # pulls out just the info from the pca results
plot(coord[,1], coord[,2]) # plots the first two axes of the pca
plot(coord[,1], coord[,2], cex= 0.1*whitewine_pca$quality) # now the symbol size tells you mpg
#text(coord[,1], coord[,2], row.names(whitewine_pca))
```



































```{r}
whitewine_pca2 = subset(whitewine_pca, select = -c(quality))
#view(whitewine_pca2)
whitewine.pca2 = prcomp(whitewine_pca2, center = TRUE, scale. = TRUE)
summary(whitewine.pca2)
#View(whitewine.pca2$rotation)
whitewine.pca2$rotation

```


```{r}

fviz_eig(whitewine.pca2)
fviz_pca_ind(whitewine.pca2,
             col.ind = "cos2", # Color by quality of representation
             gradient.cols = c("#00AFBB", "#E7B800", "#FC4E07"),
             repel = TRUE #Avoid text overlapping
             )
```


```{r}
fviz_pca_var(whitewine.pca2,
             col.var = "contrib", # Color by contributions to the PC
             gradient.cols = c("#00AFBB", "#E7B800", "#FC4E07"),
             repel = TRUE #Avoid text overlapping
             )
```


```{r}
fviz_pca_biplot(whitewine.pca2, repel = TRUE,
                col.var = "#2E9FDF", # Variables color
                col.ind = "#696969" #Individuals color
                )
```


```{r}
biplot(whitewine.pca2, choices = 1:2, scale = 1, pc.biplot = FALSE)
```


```{r}
coord = whitewine.pca2$x # pulls out just the info from the pca results
plot(coord[,1], coord[,2]) # plots the first two axes of the pca
plot(coord[,1], coord[,2], cex= 0.1*whitewine_pca2$quality) # now the symbol size tells you mpg
#text(coord[,1], coord[,2], row.names(whitewine_pca2))
```




#PCA Comparison w/ quality and w/o quality
```{r}
whitewine.pca$rotation
whitewine.pca2$rotation
```




























































